import { StyleSheet } from "react-native"

import { darkColors, fontFamilies, radii, spacing, stateTokens, typography, type ThemeColors } from "../../theme"
import { stateInteraction } from "../state/pressable"

// Warna auth hidup di src/theme (auth* + slate*): light mengikuti Stitch,
// dark memakai turunan surface/teks agar tidak pecah (R-34).

export function isDarkTheme(colors: ThemeColors): boolean {
  return colors.canvas === darkColors.canvas
}

export type AuthStyles = ReturnType<typeof createAuthStyles>

export function createAuthStyles(colors: ThemeColors, _isDark: boolean) {
  // Cabang isDark dihapus: token auth* sudah berpasangan light/dark (R-34).
  const inputBg = colors.authCard
  const outline = colors.authOutline
  const textSecondaryColor = colors.authMuted
  const titleColor = colors.authTitle

  return StyleSheet.create({
    focusRing: stateInteraction(colors).focusRing,
    ambientLeft: {
      backgroundColor: colors.accent,
      borderRadius: 160,
      bottom: -120,
      height: 320,
      left: -120,
      opacity: 0.06,
      position: "absolute",
      width: 320,
    },
    ambientRight: {
      backgroundColor: colors.accent,
      borderRadius: 160,
      height: 320,
      opacity: 0.08,
      position: "absolute",
      right: -120,
      top: -120,
      width: 320,
    },
    backButton: {
      alignItems: "center",
      backgroundColor: colors.authCard,
      borderColor: colors.authOutline,
      borderRadius: 999,
      borderWidth: 1,
      height: 44,
      justifyContent: "center",
      width: 44,
    },
    biometricButton: {
      alignItems: "center",
      backgroundColor: colors.authCard,
      borderColor: outline,
      borderRadius: radii.lg,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.row,
      justifyContent: "center",
      minHeight: 56,
      paddingHorizontal: spacing.lg,
    },
    biometricText: {
      color: titleColor,
      fontFamily: fontFamilies.semibold,
      fontSize: 14,
      fontWeight: "600",
      lineHeight: 20,
    },
    brandBadge: {
      borderRadius: 14,
      height: 56,
      marginBottom: spacing.row,
      width: 56,
    },
    brandBadgeLarge: {
      borderRadius: 16,
      height: 64,
      marginBottom: spacing.xs,
      width: 64,
    },
    checkHint: {
      alignItems: "center",
      flexDirection: "row",
      gap: 6,
      paddingHorizontal: spacing.xs,
      paddingTop: 2,
    },
    checkHintText: {
      color: textSecondaryColor,
      fontFamily: fontFamilies.medium,
      fontSize: 11,
      fontWeight: "500",
      lineHeight: 16,
    },
    checkbox: {
      alignItems: "center",
      borderColor: colors.authOutline,
      borderRadius: 6,
      borderWidth: 1,
      height: 18,
      justifyContent: "center",
      width: 18,
    },
    checkboxChecked: {
      backgroundColor: colors.accent,
      borderColor: colors.accent,
    },
    content: {
      alignItems: "stretch",
      gap: spacing.group,
      paddingBottom: spacing["2xl"],
      paddingHorizontal: 28,
      paddingTop: spacing.group,
    },
    divider: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing.md,
      paddingVertical: spacing.sm,
    },
    dividerLine: {
      backgroundColor: colors.border,
      flex: 1,
      height: StyleSheet.hairlineWidth,
    },
    dividerText: {
      color: colors.textTertiary,
      fontFamily: fontFamilies.medium,
      fontSize: 12,
      fontWeight: "500",
      lineHeight: 16,
    },
    errorBanner: {
      alignItems: "center",
      backgroundColor: colors.expenseSurface,
      borderColor: colors.expense,
      borderRadius: radii.lg,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.sm,
      padding: spacing.group,
    },
    errorBannerText: {
      color: colors.error,
      flex: 1,
      fontFamily: typography.bodyMedium.fontFamily,
      fontSize: typography.bodyMedium.fontSize,
      fontWeight: "600",
      lineHeight: typography.bodyMedium.lineHeight,
    },
    field: {
      gap: 6,
    },
    fieldError: {
      color: colors.error,
      fontFamily: typography.caption.fontFamily,
      fontSize: typography.caption.fontSize,
      fontWeight: typography.caption.fontWeight,
      lineHeight: typography.caption.lineHeight,
    },
    flex: {
      flex: 1,
    },
    footer: {
      alignItems: "center",
      gap: spacing.group,
      marginTop: spacing.sm,
    },
    footerLink: {
      color: colors.accent,
      fontFamily: fontFamilies.bold,
      fontWeight: "700",
    },
    footerText: {
      color: textSecondaryColor,
      fontFamily: typography.body.fontFamily,
      fontSize: 13.5,
      fontWeight: typography.body.fontWeight,
      lineHeight: 20,
      textAlign: "center",
    },
    forgotRow: {
      alignItems: "flex-end",
      paddingTop: spacing.xs,
    },
    forgotText: {
      color: colors.accent,
      fontFamily: fontFamilies.semibold,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    form: {
      gap: spacing.group,
    },
    header: {
      alignItems: "center",
      marginBottom: spacing.sm,
      marginTop: spacing.row,
    },
    registerHeader: {
      alignItems: "center",
      marginBottom: spacing.sm,
      marginTop: -8,
    },
    registerBrand: {
      borderRadius: 14,
      height: 56,
      marginBottom: spacing.xs,
      width: 56,
    },
    registerButton: {
      alignItems: "center",
      backgroundColor: colors.accent,
      borderRadius: radii.lg,
      elevation: 6,
      flexDirection: "row",
      gap: spacing.compact,
      justifyContent: "center",
      minHeight: 48,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 20,
    },
    registerContent: {
      alignItems: "stretch",
      gap: spacing.row,
      paddingBottom: spacing.group,
      paddingHorizontal: 28,
      paddingTop: spacing.sm,
    },
    registerFooter: {
      alignItems: "center",
      gap: spacing.sm,
      marginTop: spacing.xs,
    },
    registerForm: {
      gap: spacing.row,
    },
    registerInput: {
      color: titleColor,
      flex: 1,
      fontFamily: fontFamilies.medium,
      fontSize: 14,
      fontWeight: "500",
      minHeight: 44,
      paddingHorizontal: spacing.sm,
      paddingVertical: 0,
    },
    registerInputShell: {
      alignItems: "center",
      backgroundColor: inputBg,
      borderColor: outline,
      borderRadius: radii.lg,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.sm,
      minHeight: 48,
      paddingHorizontal: spacing.lg,
    },
    registerSubtitle: {
      color: textSecondaryColor,
      fontFamily: typography.bodyLarge.fontFamily,
      fontSize: 12,
      fontWeight: typography.bodyLarge.fontWeight,
      lineHeight: 18,
      marginTop: spacing.xs,
      maxWidth: 280,
      textAlign: "center",
    },
    registerTitle: {
      color: titleColor,
      fontFamily: fontFamilies.bold,
      fontSize: 20,
      fontWeight: "700",
      letterSpacing: -0.2,
      lineHeight: 26,
      marginTop: spacing.sm,
      textAlign: "center",
    },
    helpText: {
      color: textSecondaryColor,
      fontFamily: fontFamilies.semibold,
      fontSize: 12,
      fontWeight: "600",
    },
    input: {
      color: titleColor,
      flex: 1,
      fontFamily: fontFamilies.medium,
      fontSize: 14.5,
      fontWeight: "500",
      minHeight: 54,
      paddingHorizontal: spacing.sm,
      paddingVertical: 0,
    },
    inputShell: {
      alignItems: "center",
      backgroundColor: inputBg,
      borderColor: outline,
      borderRadius: radii.lg,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing.sm,
      minHeight: 56,
      paddingHorizontal: spacing.lg,
    },
    inputShellError: {
      borderColor: colors.error,
      borderWidth: 2,
    },
    inputShellFocused: {
      borderColor: colors.focus,
      borderWidth: stateTokens.focusWidth,
    },
    label: {
      color: titleColor,
      fontFamily: fontFamilies.semibold,
      fontSize: 13,
      fontWeight: "600",
      lineHeight: 18,
    },
    pill: {
      alignItems: "center",
      backgroundColor: colors.authSoft,
      borderColor: colors.accentSurface,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: "row",
      gap: 6,
      paddingHorizontal: spacing.md,
      paddingVertical: 2,
    },
    pillDot: {
      backgroundColor: colors.accent,
      borderRadius: 3,
      height: 6,
      width: 6,
    },
    pillText: {
      color: colors.accent,
      fontFamily: fontFamilies.bold,
      fontSize: 11,
      fontWeight: "700",
      lineHeight: 16,
    },
    pressed: {
      opacity: 0.72,
    },
    primaryButton: {
      alignItems: "center",
      backgroundColor: colors.accent,
      borderRadius: radii.lg,
      elevation: 6,
      flexDirection: "row",
      gap: spacing.compact,
      justifyContent: "center",
      minHeight: 56,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 20,
    },
    primaryButtonDisabled: {
      opacity: stateTokens.disabledOpacity,
    },
    primaryButtonText: {
      color: colors.onAccent,
      fontFamily: fontFamilies.semibold,
      fontSize: 15,
      fontWeight: "600",
      lineHeight: 22,
    },
    root: {
      backgroundColor: colors.authSurface,
      flex: 1,
      overflow: "hidden",
    },
    securityBadge: {
      alignItems: "center",
      backgroundColor: colors.authCard,
      borderColor: colors.accentSurface,
      borderRadius: 999,
      borderWidth: 1,
      flexDirection: "row",
      gap: 6,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
    },
    securityText: {
      color: textSecondaryColor,
      fontFamily: fontFamilies.medium,
      fontSize: 11,
      fontWeight: "500",
      lineHeight: 16,
    },
    subtitle: {
      color: textSecondaryColor,
      fontFamily: typography.bodyLarge.fontFamily,
      fontSize: 13.5,
      fontWeight: typography.bodyLarge.fontWeight,
      lineHeight: 20,
      marginTop: spacing.xs,
      maxWidth: 280,
      textAlign: "center",
    },
    termsRow: {
      alignItems: "flex-start",
      flexDirection: "row",
      gap: spacing.sm,
      paddingTop: spacing.xs,
    },
    termsText: {
      color: textSecondaryColor,
      flex: 1,
      fontFamily: typography.caption.fontFamily,
      fontSize: 12,
      fontWeight: typography.caption.fontWeight,
      lineHeight: 18,
    },
    termsLink: {
      color: colors.accent,
      fontFamily: fontFamilies.semibold,
      fontWeight: "600",
    },
    title: {
      color: titleColor,
      fontFamily: fontFamilies.bold,
      fontSize: 24,
      fontWeight: "700",
      letterSpacing: -0.3,
      lineHeight: 30,
      marginTop: spacing.row,
      textAlign: "center",
    },
    topBar: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: spacing.xs,
    },
  })
}
